# -*- coding: utf-8 -*-
"""Kyphosis_detection.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/10yEhpCHVFzGyFl_2vWKuhhX8dXjHWRLH

#Kyphosis Detection
"""

from google.colab import drive
drive.mount('/content/drive')

"""

## Import Libraries"""

# Commented out IPython magic to ensure Python compatibility.
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
# %matplotlib inline

"""#Get the data
- Required steps to follow:
  1. Connect google-collab to google drive
  2. Arrange the files according to directory tree as shown in Readme.md
  3. Add the created model to the directory and use it in deployment.

"""

#pd.read_csv('file_name')
df = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/Machine learning/Classification/Decision Tree Classification/Kyphosis project/kyphosis.csv')

df.head()

"""## EDA


"""

sns.pairplot(df,hue='Kyphosis',palette='Set1')

"""## Train Test Split


"""

from sklearn.model_selection import train_test_split

X = df.drop('Kyphosis',axis=1)
y = df['Kyphosis']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.30)

"""## Decision Trees

We'll start just by training a single decision tree.
"""

from sklearn.tree import DecisionTreeClassifier

model = DecisionTreeClassifier()

model.fit(X_train,y_train)

"""## Prediction and Evaluation 


"""

predictions = model.predict(X_test)

pred = model.predict(np.array([[71,3,5]]))
print(pred)

from sklearn.metrics import classification_report,confusion_matrix

print(classification_report(y_test,predictions))

print(confusion_matrix(y_test,predictions))

#Store the model parameters using Pickle libraries

import pickle
pickle.dump(model, open('kyphosis_dt_model.pkl','wb'))